spring:
  jpa:
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/cims?serverTimezone=UTC
    username: root
    password: 132135138zsl
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      max-active: 10
      initial-size: 1
      use-unfair-lock: true

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #禁用HTML页面上的“Reset All”功能
        reset-enable: false
        #用户名
        login-username: admin
        #密码
        login-password: admin
        #IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1
        #IP黑名单 (存在共同时，deny优先于allow)
        #deny: